USE f16tuning_1;

CREATE TABLE EMP
(
   EMPNO      INTEGER(4),
   ENAME      VARCHAR(10),
   JOB        VARCHAR(10),
   MGR        INTEGER(4),
   HIREDATE   DATE,
   SAL        INTEGER(4),
   COM        INTEGER(4),
   DEPTNO     INTEGER(2)
);

CREATE TABLE DETP
(
   DEPTNO   INTEGER(2),
   DNAME    VARCHAR(12),
   LOC      VARCHAR(10)
);

ALTER TABLE EMP
   ADD PRIMARY KEY(EMPNO);

ALTER TABLE DETP
   ADD PRIMARY KEY(DEPTNO);