all: LinkedListStringHW4 structConversionHW4

LinkedListStringHW4: LinkedListString_test.c
	gcc -o LinkedListStringHW4 LinkedListString_test.c

structConversionHW4: structConversion.c
	gcc -o structConversionHW4 structConversion.c
